Support g_bytes_get_data()
linuxdeepin/go-gir pull request #1
Opened 2017-05-03 04:04 UTC by kou

I don't know why `g_bytes_get_data()` is blacklisted but how about this implementation?
I think that returning `[]byte` not `size uint64, data []uint8` is suitable for `g_bytes_get_data()`.

2017-10-13 03:29 UTC, jouyouyun reviewed
g_bytes_get_data will be declaration in glib.gen.h
so delete it from glib.go.in

2017-10-13 03:35 UTC, jouyouyun reviewed
var sizeRaw C.uint64_t
will build failded on i386

2017-10-13 03:40 UTC, jouyouyun requested changes
And you should not modify the file 'glib.go.in', you should modify 'config.json', then test it on x86_64 and i386.

2017-10-19 15:16 UTC, kou commented
Done.
I confirmed that the following program works well (it outputs `<abc>(3)`) on 32bit and 64bit:

```go
package main

import "fmt"
import "gir/glib-2.0"

func main() {
	b := glib.NewBytes([]uint8{97, 98, 99});
	length, data := b.GetData();
	fmt.Printf("<%s>(%d)\n", data, length);
}
```

2017-10-20 08:25 UTC, jouyouyun commented
Merged!

2017-10-22 04:55 UTC, kou commented
Thanks. I close.

2017-10-22 04:55 UTC, closed without merging